#!/bin/bash
# /etc/init.d/thermserv

case "$1" in 
    start)
        echo "Starting thermserv"
        cd /home/pi/web;sudo node thermserv &
        ;;
    stop)
        echo "Stopping thermserv"
        sudo killall node 
	;;
    *)
        echo "Usage: /etc/init.d/thermserv start|stop"
        exit 1
        ;;
esac

exit 0
